### PR TITLE
feat: Floyd-Warshall Algorithm

### PR DESCRIPTION
**Pull request by crypto-cmd**
## What?
I've implemented Floyd-Warshall Algorithm. It is a solution to issue #21 

## Why?
The repo is a WIP and I wished to help contribute to  @yangshun 's open-source project. :)

## Testing?
I've run ` yarn check-all ` which gave the following results for floydWarshallAlgorithm.ts:

Screenshot (152)

### CODE REVIEW

**Review by mauris — APPROVED** [review]
Great work here @crypto-cmd. Thank you for writing this!

**Comment by crypto-cmd** [comment]
Thanks @mauris ! :) You're very welcome.

**Review by yangshun — APPROVED** [review]
Thank you very much!

**Comment by crypto-cmd** [comment]
@yangshun No problem :) 
Remember to close the related issue

**Pull request merged**
