### PR TITLE
Add Graph Data Structure

### PR DESCRIPTION
**Pull request by utkarsh261**
Hopefully solves #12 and #36 . Tests included.

Some code inspired by [this](https://github.com/trekhleb/javascript-algorithms/tree/master/src/data-structures/graph) javascript library.

### CODE REVIEW

**Review by yangshun — CHANGES_REQUESTED** [review]
Thanks for the PR! I have some question regarding the design of the data structures. What's the point of nodes having neighbors when there are edges?

**Comment by utkarsh261** [comment]
I did that keeping in mind the general use cases, for example in BFS or DFS the only thing you need are the immediate neighbors of the current node, so to make it faster, we can keep them in a list for each node, so that the traversal gets faster and we can get them easily through getAllNeighbors(). 
And I realized this is the most trivial way to do this.
On the other hand, if we have record of all the edges in the graph, we can fasten up operations that involves edges, like Kruskal's Algorithm for MST.

**Comment by yangshun** [comment]
I don't think we should have two ways of defining neighbors. The relationship should just be defined using edges.

I'd opt to go for the APIs defined on https://en.wikipedia.org/wiki/Graph_(abstract_data_type). Would you like to make the changes? Alternatively I could merge this first and make the changes myself. Lemme know!

**Comment by utkarsh261** [comment]
My branch is a little messed up, Please merge it then we can make the changes as you like it.

**Pull request merged**
